### ISSUE TITLE
使用vscode编译报错”LNK2019: 无法解析的外部符号 gluPerspective“等

### ISSUE THREAD

**Issue by WhizZest** [chunleili/miniGL#1]
环境：win11，vscode，vs2019编译器。
报了很多类似报错”LNK2019: 无法解析的外部符号 gluPerspective“的错误。
查了下，是缺少了glu库，在CMakeLists.txt中增加代码可解决问题：
```cmake
# glu
find_package(GLU REQUIRED)
target_link_libraries(main OpenGL::GLU)
```

**Comment by chunleili** [comment]
> 环境：win11，vscode，vs2019编译器。 报了很多类似报错”LNK2019: 无法解析的外部符号 gluPerspective“的错误。 查了下，是缺少了glu库，在CMakeLists.txt中增加代码可解决问题：
> 
> ```cmake
> # glu
> find_package(GLU REQUIRED)
> target_link_libraries(main OpenGL::GLU)
> ```

感谢。确实有这个问题。按照您提供的方案已经解决。
